- sdk/data_manager_test.go
- sdk/devices_test.go
- sdk/logger/logger_test.go
This PR adds in additional test cases. 
- device enumeration (dynamic device config)
- data manager reads
- came across a race condition when writing some tests which I believe are related to the test setup themselves, not the actual code. (those tests are currently commented out)
- logger tests
related: #152
> add additional test cases

- sdk/data_manager.go
- sdk/data_manager_test.go
- sdk/devices.go
- sdk/models.go
- sdk/version.go
This PR implements bulk read functionality (described in Section 4.3.3 of the SDK 1.0 design doc). This work was done now as opposed to with the 1.0 rev because it is needed in the short term.
There will be a corresponding PR for the I2C plugin changes with this.
Once this is merged, I'll cut a new release for 0.6.0
> Support for bulk reading

- examples/auto_enumerate/plugin.go
- examples/c_plugin/plugin.go
- examples/multi_device_plugin/plugin.go
- examples/pre_run_actions/plugin.go
- examples/simple_plugin/plugin.go
- sdk/config/plugin.go
- sdk/config/plugin_test.go
- sdk/config/v1.0-plugin.go
- sdk/config/v1.0-plugin_test.go
- sdk/data_manager_test.go
- sdk/meta.go
- sdk/meta_test.go
- sdk/plugin.go
- sdk/plugin_test.go
fixes #190
This PR takes out the `name` from the config and moves it and other plugin metainfo to a dedicated metainfo struct. This info gets logged out on startup right now. Later, it can be surfaced to synse server via gRPC.
> add static plugin metainfo, move metainfo out of config

- sdk/cfg/config.go
- sdk/cfg/device.go
- sdk/cfg/device_test.go
- sdk/cfg/validation.go
- adds a ConfigComponent interface
- adds logic to the SchemeValidator to call Validate on all structs that implement the ConfigComponent interface
- update fields with struct types to be pointers to struct types
- update tests
fixes #211 
fixes #212
> add config component interface, update component validation behavior

- sdk/cfg/config.go
- sdk/cfg/config_test.go
- sdk/cfg/device.go
- sdk/cfg/device_test.go
- sdk/cfg/plugin.go
- sdk/cfg/reader.go
- sdk/cfg/validation.go
- sdk/errors/errors.go
- sdk/errors/validation.go
This adds in an updated scheme for the plugin config, updates the ConfigComponent validation method so we can collect all errors and not just the first one (if there are multiple). Adds some tests, and lays down the initial work for reading in the plugin config. 
The dynamic registration piece still needs to be figured out, but I am considering that a separate issue, since there is a bunch of other work that needs to happen for that bit of functionality.
Related to:
- #213 
- #198 
- #194
> Updates to the plugin configuration

- internal/test/env.go
- internal/test/file.go
- sdk/cfg/device.go
- sdk/cfg/plugin.go
- sdk/cfg/plugin_test.go
- sdk/cfg/reader.go
- sdk/cfg/reader_test.go
- sdk/cfg/validation.go
- sdk/cfg/validation_test.go
- sdk/cfg/versioning.go
- sdk/cfg/versioning_test.go
This adds in tests for the new config pieces for SDK v1. Test coverage for the new config is at around 98%.
There are still some cases I want to add tests for, but I'll open separate issues for that. This is big enough as it is.
With these tests providing some amount of verification that things are working as intended, this should fix #213, #209, and makes #195 effectively complete.
> Add tests for updated SDK configuration package

- sdk/defaults/defaults.go
- sdk/flags.go
- sdk/plugin.go
- sdk/policies/constraints.go
- sdk/policies/constraints_test.go
- sdk/policies/policies.go
- sdk/policies/policies_test.go
- sdk/version.go
- sdk/version_test.go
This is a fairly dirty PR that adds in policies and constraints, adds in basic command line flags for the plugin, adds in tests, and starts to frame up how the new `sdk.Plugin` will look. There are a few places that need to be cleaned up, but that will wait until the new Plugin is more developed and stable.
> Add in config policies and constraints

- sdk/cfg/plugin.go
- sdk/cfg/plugin_test.go
- sdk/cfg/reader.go
- sdk/cfg/reader_test.go
- sdk/policies/policies_test.go
fixes #223 
this PR makes reading in Plugin configs and Device configs use the same code paths, and removes some unnecessary dependencies. Moves specifying default values into struct field tags.
> make config reading more uniform across all config types

- sdk/defaults.go
- sdk/defaults/defaults.go
- sdk/plugin.go
This work originally started as trying to do the "plugin as an interface" work (section 4.1.4), but after doing some experimentation there and some research, I found a better, cleaner approach. 
This introduces a "PluginOption", which basically can be set for each bit of functionality a user wants to customize. Instead of having to define a struct that implements X number of interfaces, like was planned, or jam a bunch of functions/`nil`s into a Handlers struct, like we were doing before, the Plugin should now take in whatever options the author specifies and apply those. For anything that hasn't been specified, default options will be applied. 
This means we get an interface like this for simple plugins that need no additional configuration:
```go
plugin := sdk.NewPlugin()
```
And like …
> Update Plugin API to use PluginOptions

- sdk/actions.go
- sdk/config/device.go
- sdk/devices.go
- sdk/flags.go
- sdk/meta.go
- sdk/options.go
- sdk/plugin.go
- sdk/type.go
- sdk/type_test.go
- sdk/utils.go
This PR does a lot of the rework for device registration flow. There is still work to do there, but the basics are either there or sketched out, so it should just be a matter of filling it in.
This also makes a bunch of data structures global to the SDK, instead of plugin-specific. There is still some work to do with this, but it should make things a bit easier because we now shouldn't have to pass along a reference to the plugin everywhere and then traverse fields to get the info we want.
Related:
- #186
> Rework of the device registration flow, make some data global

- sdk/config/plugin.go
- sdk/plugin.go
- sdk/policies/policies.go
Fixes #237
There was some additional stuff that could have gone into here, particularly around retries / re-registration of the dynamic registration functions, but that got deep into the weeds and just opened up more questions for me.
Ultimately, it should really be up to the user (at least for now) to implement retries, etc. as needed. Its hard to build that functionality in because the use cases for it can vary so much. Perhaps re-registration/retry will be added at a later date. For now, I think this is good enough.
> Add basic scheme for dynamic registration config

- sdk/actions.go
- sdk/devices.go
- sdk/plugin.go
- sdk/server.go
- sdk/utils.go
- sdk/version.go
- sdk/version_test.go
This PR:
- adds support for post-run actions (#85)
- adds a socket-cleanup post-run action (#14)
- cleans up utils.go (#232)
- makes the version a global var instead of a function call
- various other bits of cleanup/reorganization
> Implement post-run actions, cleanup

- sdk/config/device.go
- sdk/config/device_test.go
- sdk/config/plugin_test.go
- sdk/context.go
- sdk/context_test.go
- sdk/defaults.go
- sdk/defaults_test.go
- sdk/options.go
- sdk/options_test.go
- sdk/plugin.go
fixes #258 
@Kontazler this can be used for doing validation of the door lock config when we upgrade to sdk1.0
> add support for custom data validation functions

- Gopkg.lock
- sdk/meta.go
- sdk/meta_test.go
- sdk/server.go
fixes #271 
this PR adds in a `Tag` field to the metainfo, where the maintainer and name are normalized into a namespaced identifier for a plugin.
> Apply namespacing conventions to metainfo tag

- Gopkg.lock
- Gopkg.toml
- sdk/device.go
- sdk/errors/errors.go
This PR adds plugin sort ordinal for SNMP scans. By default it's zero for unordered scans. For ordered scans, it's up to the plugin to determine the sort order to use. Synse will order by plugin, sortOrdinal.
This is running on Wrigley.
Requires:
https://github.com/vapor-ware/synse-server-grpc/pull/29
dep update
PRs for the snmp, synse pending.
> Add SortOrdinal.

- Gopkg.lock
- examples/listener/.gitignore
- examples/listener/Makefile
- examples/listener/README.md
- examples/listener/config.yml
- examples/listener/config/device/pusher.yaml
- examples/listener/plugin.go
- examples/listener/pusher/main.go
- sdk/data_manager.go
- sdk/data_manager_test.go
- sdk/device.go
- sdk/plugin.go
#303 
This PR does the bulk of the work for adding a listener as an option to a device handler. It includes a simple example with this working. 
This PR will go into the v1.2.0-staging branch, waiting for other 1.2.0 work to be done before merging into master and cutting a new release.
> add basic support for handler listener function

- sdk/config.go
- sdk/config_test.go
- sdk/plugin.go
- sdk/validate_test.go
#306
This PR disables the check on the minor version of the config field annotated version for addedIn/deprecatedIn/removedIn -- now all checking is only done on the major version. 
This preserves compatibility for the current version (we can specify 1, 1.0, 1.1, 1.2, ...) as the config version and all of them are valid. 
I added some notes where things should be changed/simplified/removed for v2. I've also started a v2 project to start tracking some of these issues.
> simplify scope of config field versioning

- sdk/config.go
- sdk/device.go
- sdk/reader.go
fixes #309
this pr:
- logs the device config when a duplicate device ID is found
- logs plugin config at INFO level by default (was DEBUG)
- more context information with files/paths of config files used
The below snippet shows all of the above changes:
```
INFO[0000] [sdk] found config files                      configs="[config.yml]" path=/Users/edaniszewski/go/src/github.com/vapor-ware/synse-sdk/examples/multi_device_plugin
INFO[0000] [sdk] plugin config: {"Version":"1","Debug":true,"Settings":{"Mode":"serial","Read":{"Enabled":true,"Interval":"5s","Buffer":100},"Write":{"Enabled":true,"Interval":"5s","Buffer":100,"Max":100},"Transaction":{"TTL":"8m"}},"Network":{"Type":"unix","Address":"example-plugin.sock","TLS":null},"DynamicRegistration":{"Config":[]},"Limiter":null,"Health":{"UseDe …
```
> updates to device and config logging

- Gopkg.lock
- Gopkg.toml
- internal/test/grpc.go
- sdk/cache.go
- sdk/cache_test.go
- sdk/data_manager.go
- sdk/data_manager_test.go
- sdk/device.go
- sdk/device_test.go
- sdk/plugin.go
- sdk/plugin_test.go
- sdk/server.go
- sdk/server_test.go
- sdk/type_test.go
- sdk/utils.go
- sdk/utils_test.go
#305 
This PR adds a configurable windowed cache for storing plugin data locally. If disabled, it behaves like it does currently. The new ReadCached grpc route will just return a dump of all the current readings.
If enabled, each reading will be cached for a configurable amount of time. This means that we can get better data resolution if we need it. Read would still get the current reading, but historical things (like blackbox) could get a dump of the reading cache to see all the readings (which could be useful since otherwise the resolution would be tied to the poll rate, which may lose lots of data depending on how slow it is - this is particularly the case with push-based data sources).
> Windowed cache

- sdk/type.go
- sdk/type_test.go
fixes #313 
@MatthewHink I believe this should fix the scaling factor issue. Now, if no scaling factor is set, the value is returned as-is. If a scaling factor is set, the value will be multiplied by it and will always be returned as a float64. 
the issue was the improper assumption that the type of the value had to remain consistent before and after the scaling, but in actuality, the only time a specified type matters is when converting if from bytes, e.g.
> update how scaling factor is applied

- Gopkg.lock
- sdk/device.go
- sdk/plugin.go
- sdk/utils_test.go
Tested on the VEM with i2c master. We can now see how long calls are taking. Previous traces were seconds only.
```
time="2018-11-15T21:19:12.672Z" level=debug msg="SDP610 reading channel 1."
time="2018-11-15T21:19:12.674Z" level=debug msg="channel 1, chReading \x01, readChannel 1"
time="2018-11-15T21:19:12.674Z" level=debug msg="OK: set differential pressure channel to: 1"
time="2018-11-15T21:19:12.694Z" level=debug msg="[grpc] devices rpc request" request=
time="2018-11-15T21:19:12.865Z" level=debug msg="SDP610 reading channel 1 returning [-191.89999999999998 -165.29999999999998 -
```
> Log time in milliseconds.

- .jenkins
When working on migrating other repos to Jenkins, I noticed that Jenkins uses a second workspace for things that run in docker vs. things that run on the host node. This isn't a huge deal here since we aren't generating build artifacts for releases, etc, but I wanted to update here to remain consistent with how we will be doing it in other places. Plus, if we do eventually want to use build artifacts from a container, this will mean we are already set up to do so.
> reuse node for docker stages in ci

- Gopkg.lock
- Gopkg.toml
- sdk/data_manager.go
- sdk/health/health.go
- sdk/health/health_test.go
- sdk/models.go
- sdk/server.go
- sdk/transaction.go
- sdk/transaction_test.go
#323
This PR only lays down some of the framing work around this. The build will fail as there are components that are not yet updated, as doing so would be going down a bunch of rabbit holes that would make this PR massive.
The goal here is simply to update the server function signatures and some of the v3 message types. Future PRs will add back in the functionality that was disabled here and will continue to propagate the updates appropriately.
> update server to use v3 grpc API

- sdk/server.go
- sdk/version.go
#323 
Updates the core test/version routes so that they should be usable, bump internal sdk version to 3
> update the core grpc v3 routes

- sdk/config/config.go
- sdk/config/plugin.go
- sdk/device_manager.go
- sdk/plugin.go
- sdk/scheduler.go
- sdk/server.go
with the simple example plugin:
```
INFO[0000] [config] loading configuration                ext=yaml loader=plugin name=config paths="[. ./config /etc/synse/plugin/config]"
INFO[0000] [config] found valid config                   file=config.yml loader=plugin path=. policy=optional
INFO[0000] Plugin Info:                                 
INFO[0000]   Tag:         vaporio/simple-plugin         
INFO[0000]   Name:        simple plugin                 
INFO[0000]   Maintainer:  vaporio                       
INFO[0000]   VCS:                                       
INFO[0000]   Description: A simple example plugin       
INFO[0000] Version Info:                                
INFO[0000]   Plugin Version: 1.0                        
INFO[0000]   SDK Version:    3.0.0 …
```
> improve plugin startup logging

- Gopkg.lock
- Gopkg.toml
- examples/device_actions/plugin.go
- examples/health_check/plugin.go
- sdk/config/config.go
- sdk/config/plugin.go
- sdk/device.go
- sdk/device_manager.go
- sdk/health/manager.go
- sdk/meta.go
- sdk/plugin.go
- sdk/plugin_handlers.go
- sdk/plugin_test.go
- sdk/scheduler.go
- sdk/sdk.go
- sdk/server.go
- sdk/state_manager.go
- sdk/tag.go
- sdk/transaction.go
- sdk/utils/time.go
- sdk/version.go
it is the current best practice to import logrus with lowercase `Sirupsen`. this is a nice to have, as the built-in vendoring solution for go will trip up if it is specified as capitalized and will not follow the redirect.
while not critical for us right now, as we still use dep, we may move away from that when it is deprecated, and other plugin authors may prefer to use the built-in vendoring.
> normalize logging import name

- sdk/scheduler_test.go
fixes a test failure that showed up in CI, but not locally. this was due to the write timeout not being set on the device used for the test, so the write terminated early in error, when it was expected to complete in success state.
> fix test failure in CI

- Gopkg.lock
- sdk/server.go
- sdk/server_test.go
this PR makes changes to the SDK corresponding to the gRPC changes here: https://github.com/vapor-ware/synse-server-grpc/pull/48
providing the plugin ID via the gRPC API makes it easier for Synse Server to identify plugins and mitigates the need for additional plugin->device mapping
> update metadata and device response to provide plugin id

- Gopkg.lock
- Gopkg.toml
- sdk/scheduler.go
- sdk/scheduler_test.go
- sdk/server_test.go
- sdk/state_manager.go
- sdk/state_manager_test.go
- sdk/transaction.go
- sdk/transaction_test.go
updates the method to create a new transaction to use a custom transaction ID if specified. propagates an error if a transaction with that ID already exists. adds and updates tests.
> honor custom transaction IDs supplied by the caller

- sdk/alias.go
- sdk/alias_test.go
- sdk/device_manager.go
- sdk/device_manager_test.go
- sdk/server.go
- sdk/server_test.go
fixes #414 
adds an AliasCache to the device manager. When devices are registered with the manager, it maps tha alias to the device. 
When resolving a device via Selector, it will check if the specified ID corresponds to a device. If not, it will try to use that ID as the alias key for lookups. This means anything calling the gRPC API can use device ID / device alias interchangeably.
> add support for device alias lookups

- Gopkg.lock
- examples/multi_device_plugin/config.yml
- sdk/config/plugin.go
- sdk/config/plugin_test.go
- sdk/metrics.go
- sdk/plugin.go
fixes #415 
This PR adds very basic support for exposing application metrics with Prometheus. It just uses the default metrics for the time being. If we want, we can look into adding more metrics in the future (e.g. number of grpc requests, number of reads, number of writes, ...)
> add prometheus exporter for basic plugin application metrics

- sdk/config/device.go
- sdk/device.go
- sdk/device_test.go
- sdk/output/output_test.go
- sdk/output/reading.go
- sdk/output/reading_test.go
- sdk/scheduler.go
- sdk/scheduler_test.go
This PR:
- allows reading context data to be specified in device configuration
- simplifies the API around adding reading context 
- adds and updates tests
- removes the "info" field from a reading, since that was essentially just a stand-in for the reading context.
> add missing support for reading context

- sdk/health/manager.go
fixes #431 
removes logging which will happen on every health check as it was polluting the logs. only log when there is a change in health state.
> reduce chattyness of health file logs

- Gopkg.lock
- Gopkg.toml
- internal/test/grpc.go
- sdk/server.go
- sdk/server_test.go
- sdk/state_manager.go
- sdk/stream.go
- sdk/stream_test.go
introduces streamed readings support to the SDK
this PR requires some cleanup, but opening for initial review + feedback.
related:
- https://github.com/vapor-ware/synse-server/pull/322
- https://github.com/vapor-ware/synse-server-grpc/pull/57
> streamed readings

- examples/c_plugin/config/device/temperature.yaml
- examples/device_actions/config/device/airflow.yaml
- examples/device_actions/config/device/temperature.yaml
- examples/device_actions/plugin.go
- examples/dynamic_registration/plugin.go
- examples/health_check/config/device/test.yaml
- examples/listener/config/device/pusher.yaml
- examples/multi_device_plugin/config/device/airflow.yaml
- examples/multi_device_plugin/config/device/temperature.yaml
- examples/multi_device_plugin/config/device/voltage.yaml
- examples/simple_plugin/config/device/led.yaml
- examples/simple_plugin/config/device/test.yaml
- sdk/config/device.go
- sdk/config/testdata/device/1.yaml
- sdk/config/testdata/device/2.yaml
- sdk/device.go
- sdk/device_test.go
- sdk/testdata/device/config.yml
- sdk/version.go
This PR:
- removes the `metadata` device configuration. its role has effectively been replaced with the `context` configuration
- surface the context info to Synse Server via the gRPC API (previously where metadata was being surfaced)
The `metadata` and `context` fields were both filling similar, but slightly different roles. Metadata just stayed with the device, while Context was associated with the device and its readings. It doesn't seem like we'd want device-only metadata which isn't also part of the reading context, so the Metadata config becomes superfluous and can be replaced wholesale with the context.
> replace device metadata with device context

- sdk/config/plugin.go
- sdk/plugin.go
- sdk/version.go
This PR:
- fixes a bug where metrics config wasn't being logged out
- adds a fix for a go1.13 bug where parsing custom flags in `init()` causes `go test` to not work correctly
- bumps SDK version to `3.0.0-alpha.3`
> fix logging bug, fix go1.13 testing bug, bump version

- sdk/config/plugin.go
- sdk/utils/redact.go
- sdk/utils/redact_test.go
This PR:
- ports the password redaction work from https://github.com/vapor-ware/synse-sdk/pull/441 (merged to master) to the v3 branch. since a bunch of things have changed from master->v3, simply cherry picking the commit wouldn't work.
With this PR, the v3 branch will have all new features in the master branch.
> port password redact feature from master to v3 branch

- sdk/device.go
- sdk/device_test.go
This PR:
- fixes a bug in the `NewDeviceFromConfig` builder which, when property inheritance is enabled, merged into the prototype maps (data, context), mutating the state for any future instances that are built off of the same prototype. This fix copies the prototype maps to ensure the actual prototype state is not mutated.
- adds regression test for the bug
shoutout to @KylerBurke for finding the bug! :bug:
> bugfix: update device builder to copy prototype map to prevent it from being mutated

- sdk/device.go
- sdk/device_manager.go
- sdk/device_test.go
This PR:
- updates the function signature of the primary device building function, `NewDeviceFromConfig`, so that a device handler map can be passed to it. this moves the association of the device handler (via its name) from the DeviceManager (on `Add`) to the device builder, which logically makes more sense anyways.
- this change makes it easier for plugins using dynamic registration (e.g. SNMP) to actually build devices instead of having to go through some side steps, particularly for writing tests for such plugins.
This is my initial thought on how to make things easier for dynamic plugins. One other possibility is for the `Device.handler` private field to be made public (`Device.HandlerFn`, or replace the `Device.Handler  string` which holds the handler name with `Device.Handler …
> pass handler map to device builder to make building devices easier for dynamic pluings

- sdk/output/builtins.go
This PR:
- adds more built-in output types (millisecond, nanosecond, microsecond, volt-second, switch)
> add more built-in output types

- sdk/device.go
- sdk/device_manager.go
- sdk/device_test.go
- sdk/tag.go
- sdk/tag_test.go
This PR:
- adds support  for basic `env` templates in device `tags` configuration.
- adds support for basic `env` templates in device `context` configuration.
- adds and updates tests
fixes #447
> feat: allow basic templating in tag and context configuration

- sdk/config/device.go
- sdk/config/device_test.go
- sdk/device.go
- sdk/device_test.go
- sdk/scheduler.go
- sdk/scheduler_test.go
- sdk/transform.go
- sdk/transform_test.go
This PR:
- changes the device config
- removes instance ScalingFactor config
- removes instance Apply config
- adds Transformers config which allows specifying multiple scales/apply transforms in an ordered list
- adds and updates tests
With this, a config snippet like:
```yaml
devices:
- type: foo
instances:
- info: Device 1
scalingFactor: 0.1
apply:
- FtoC
```
becomes
```yaml
devices:
- type: foo
instances:
- info: Device 1
transforms:
- scale: 0.1
- apply: FtoC
```
this allows you to specify order because it is a list, so if you want to apply before scale, 
```yaml
devices:
- type: foo
instances:
- info: Device 1
transforms:
- apply: FtoC
- scale: 0.1
```
fixes #449
> update apply/scale transform config for ordering and flexibility

- sdk/config/plugin_test.go
- sdk/utils/redact.go
- sdk/utils/redact_test.go
This PR:
- fixes a bug where the dynamic config wasn't being password redacted properly.
related: https://github.com/vapor-ware/synse-snmp-plugin/issues/45
> bugfix: add missing type check for redacting dynamic config

- sdk/utils/redact.go
- sdk/utils/redact_test.go
This PR:
- fixes a bug in the redact password implementation in which slice types did not work with copies of the data, so they were mutating the input config
related: https://github.com/vapor-ware/synse-snmp-plugin/issues/47
> bugfix: redacting slice types should copy data to not overrwrite

- sdk/config/config.go
- sdk/utils/redact.go
- sdk/utils/redact_test.go
This PR:
- updates the RedactPasswords utility to make it a bit more flexible in the inputs it can handle
- logs out plugin and device configurations
related to #453 
an example of what these changes look like:
```
INFO[0000] [config] loading configuration                ext=yaml loader=plugin name=config paths="[. ./config /etc/synse/plugin/config]" policy=optional
INFO[0000] [config] found matching config                file=config.yml loader=plugin path=. policy=optional
INFO[0000] [config] reading config file                  file=config.yml
INFO[0000] [config] successfully loaded configuration data  data="map[debug:true dynamicRegistration:map[config:[map[port:1234 somethingPassphrase:REDACTED]]] health:map[healthFile:] metrics:map[enabled:true] network:map[address::5001 type:tcp] …
```
> Configuration logging updates

- sdk/output/builtins.go
This PR:
- fixes a small bug where some built-in output types were not formatted consistently. my bad for not being more diligent when  adding them in before!
> bugfix: format names of built-in output types consistently

- sdk/device_manager.go
This PR:
- adds in missing context information to logging when dynamic device handlers fail to properly load/create devices.
> bugfix: add error context to log message for failed dynamic device load/create

- sdk/models.go
- sdk/models_test.go
- sdk/plugin.go
- sdk/scheduler.go
- sdk/scheduler_test.go
- sdk/server.go
- sdk/server_test.go
- sdk/state_manager.go
- sdk/state_manager_test.go
- sdk/stream.go
- sdk/stream_test.go
- sdk/version.go
- Main change is in models.go
- Changed the stateManager to have deviceManager as a member because the deviceManager manages devices and the stateManager needs access to them to create ReadContexts.
- Test changes to keep them running.
Putting this PR up to get the okay on it prior to making changes to the plugins. Will not merge w/o associated plugin PRs / SDK release / deployment changes.
Fixes: https://github.com/vapor-ware/synse-sdk/issues/462
>  Device in read and write contexts rather than device id.

- sdk/output/builtins.go
This PR:
- adds additional basic output types
these output types were useful in describing some values from SNMP MIB devices and will likely be useful elsewhere.
> feat: add additional output types

- sdk/scheduler.go
- sdk/scheduler_test.go
This PR:
- adds a check for nil reading value before applying transform function(s)
- adds a test case for the above
- fixes comment in unit test
fixes #468
> bugfix: do not apply transform function if reading value is nil

- sdk/device_handler.go
- sdk/plugin.go
- sdk/plugin_test.go
- sdk/scheduler.go
This PR:
- adds deprecation notices for the DeviceHandler  `Listen` function
- adds exported `AddDevice` and `NewDevice` functions off of the plugin struct - this should  make it easier for a plugin to create/register devices at runtime.
Related: #466
> Updates to better support streaming  protocol

- sdk/scheduler.go
- sdk/scheduler_test.go
This PR:
- fixes two bugs (should be  `return` not `break`) in read/write scheduler. This doesn't really affect the main run logic - but it does affect test logic in being able  to terminate the goroutine.
- adds tests to verify that schedule reads does actually run everything in  serial when  configured for serial and in  parallel when  configured in  parallel
> bugfix: exit read/write schedule loops on channel close; add tests for serial/parallel schedule

- go.mod
- go.sum
- sdk/device_manager.go
- sdk/device_manager_test.go
This PR:
- adds glob matching capabilities to device action filtering, making it more flexible for which devices an action can match against.
- adds unit tests
fixes  #478 
This is needed for  the emulator plugin, where we want to create a device config set which more closely matches what we have running in production. In order for the emulator to register devices correctly with their backends for generating fake metrics, we need to use device setup actions, but the device types for some things we use in production do not match with what the expected filter constraint is (e.g. emulator expects a "fan" type, but we have an  "ecblue.fan" type). By adding in this glob matching,  we can accommodate these kinds of types and achieve a configuration  which more closely  matches  production.
> feat: add glob matching to device action filters

- sdk/tag.go
- sdk/tag_test.go
In the OC plugin, I was occasionally seeing:
```
fatal error: concurrent map writes
goroutine 310 [running]:
runtime.throw(0xbbf525, 0x15)
/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc000453f50 sp=0xc000453f20 pc=0x42f4f2
fatal error: concurrent map writes
runtime.mapassign_faststr(0xac0a60, 0xc0001a0840, 0xbb31a8, 0x4, 0xc00007a158)
/usr/local/go/src/runtime/map_faststr.go:291 +0x3fe fp=0xc000453fb8 sp=0xc000453f50 pc=0x4133ee
text/template.(*Template).associate(0xc0001a8700, 0xc0001a8700, 0xc0010aaf00, 0xc0017ea401)
/usr/local/go/src/text/template/template.go:226 +0xb7 fp=0xc000453ff8 sp=0xc000453fb8 pc=0x5b5607
text/template.(*Template).AddParseTree(0xc0001a8700, 0xbb31a8, 0x4, 0xc0010aaf00, 0x0, 0x0, 0x0)
/usr/local/go/src/text/template/template.go:132 +0xf9 fp=0xc000454048 …
```
> bugfix: fix race condition around template.Parse when called concurrently, add tests

- sdk/scheduler.go
- sdk/scheduler_test.go
This PR:
- adds in write delay, which was previously configurable, but its usage was not implemented
- adds regression test
related to #489
> bugfix: add missing delay usage for writes
