vapor-ware/synse-sdk

- sdk/utils.go
> fix bug in device registration when a prototype is not found

- examples/auto_enumerate/Makefile
- examples/auto_enumerate/plugin.go
- examples/c_plugin/Makefile
- examples/c_plugin/plugin.go
- examples/multi_device_plugin/Makefile
- examples/multi_device_plugin/plugin.go
- examples/pre_run_actions/Makefile
- examples/pre_run_actions/plugin.go
- examples/simple_plugin/Makefile
- examples/simple_plugin/plugin.go
- sdk/plugin.go
- sdk/plugin_test.go
- sdk/version.go
- sdk/version_test.go
> simplify plugin versioning info

- sdk/cfg/config.go
- sdk/cfg/environment.go
- sdk/cfg/reader.go
This PR lays down most of the groundwork for #209 
It also starts to address #210
This doesn't complete either of those issues, but it is a good "break" point. To finish these up, it will likely take a bit of a heftier PR, so just opening this bit now instead of shoving it all into one massive PR.
> Groundwork for an updated config file reading flow

- sdk/cfg/unification.go
- sdk/cfg/verification.go
- sdk/errors/validation_test.go
- sdk/errors/verification.go
- sdk/errors/verification_test.go
- sdk/plugin.go
- sdk/version.go
This PR largely just cleans up a few things and outlines the general flow for the plugin. This will help soon when working on different parts of this flow.
> Add more custom errors, tests, and outline the plugin flow

- sdk/devices.go
- sdk/plugin.go
This is a small PR that mostly cleans some small things up.
> Update plugin flow to add in error propagation, some cleanup

- Gopkg.lock
- sdk/data_manager.go
- sdk/devices.go
- sdk/errors/plugin.go
- sdk/errors/plugin_test.go
- sdk/models.go
- sdk/plugin.go
- sdk/transaction.go
- sdk/type.go
- sdk/utils.go
- sdk/validate.go
This addresses:
- #242 
- #241 
- #240 
- #235 
- #231 
- #203 
- #187
> Updates for data modeling, plugin flow, validation, and other small pieces

- sdk/context.go
- sdk/devices.go
- sdk/meta.go
- sdk/models.go
- sdk/options.go
- sdk/plugin.go
- sdk/verification.go
> Add global plugin context, cleanup, reorganization

- Gopkg.lock
- sdk/data_manager_test.go
- sdk/devices_test.go
- sdk/models_test.go
- sdk/plugin.go
- sdk/plugin_test.go
- sdk/server.go
- sdk/transaction_test.go
- sdk/utils_test.go
related to:
- #236 
- #203 
In addition to adding the handler functions for the server, this comment out a LOT of old tests. These tests need to be re-written/updated for all the new stuff. Just commenting them out now so that when I do start doing that (soon), I can run tests without failures.
> Implement handlers for the plugin grpc server

- sdk/actions_test.go
- sdk/config/unification_test.go
- sdk/context_test.go
- sdk/data_manager.go
- sdk/defaults_test.go
- sdk/devices.go
- sdk/errors/errors.go
- sdk/models.go
- sdk/options_test.go
- sdk/plugin.go
- sdk/server.go
- sdk/transaction.go
- sdk/validate.go
- sdk/validate_test.go
- sdk/verification.go
- sdk/verification_test.go
- sdk/version.go
Various pieces of cleanup, organization, simplification, renaming, documenting. Nothing too big.
> Cleaning, organizing, documenting

- .circleci/config.yml
- Makefile
- examples/dynamic_registration/plugin.go
> add example verification to ci, fix example

- sdk/config.go
- sdk/config_test.go
- sdk/default.go
- sdk/default_test.go
- sdk/flags.go
- sdk/flags_test.go
- sdk/plugin.go
- sdk/plugin_test.go
- sdk/policies/policies.go
- sdk/server.go
- sdk/server_test.go
- sdk/testdata/device/invalid.yml
- sdk/testdata/device/ok.yml
- sdk/testdata/output_type/invalid.yml
- sdk/testdata/output_type/ok.yml
- sdk/testdata/plugin/invalid/config.yml
- sdk/testdata/plugin/ok/config.yml
- sdk/utils.go
- sdk/utils_test.go
- sdk/verification.go
- sdk/verification_test.go
this does some cleaning and reorganizing, and also adds in a bunch of missing tests. this also fixes some bugs that the tests discovered.
related:
- #221 
- #238 
- #189
> add tests and do some cleaning

- Gopkg.lock
- Makefile
- examples/c_plugin/plugin.go
- examples/device_actions/devices/air8884.go
- examples/device_actions/devices/temp2010.go
- examples/dynamic_registration/plugin.go
- examples/health_check/plugin.go
- examples/multi_device_plugin/devices/air8884.go
- examples/multi_device_plugin/devices/temp2010.go
- examples/multi_device_plugin/devices/volt1103.go
- examples/simple_plugin/plugin.go
- sdk/data_manager_test.go
- sdk/device.go
- sdk/device_test.go
- sdk/models.go
- sdk/models_test.go
- sdk/type_test.go
opening this PR now so I have a place to ask questions, still a WIP
> Updates and bug fixes to SDK

- sdk/device.go
> remove some debug logging

- Gopkg.lock
- examples/dynamic_registration/plugin.go
- examples/health_check/plugin.go
- examples/simple_plugin/plugin.go
- sdk/data_manager.go
- sdk/reader.go
- sdk/scripts/command.go
- sdk/utils.go
> fix linting issues

- sdk/config.go
- sdk/context.go
- sdk/default.go
- sdk/device.go
- sdk/device_handler.go
- sdk/device_manager.go
- sdk/handlers.go
- sdk/plugin.go
- sdk/server.go
- sdk/tag.go
- sdk/type.go
- sdk/validate.go
This PR does some cleanup and commenting out. It continues to piece together the device flow and consolidating similar pieces.
> v3 device updates, pt 2

- sdk/context.go
- sdk/device.go
- sdk/device_handler.go
- sdk/device_manager.go
- sdk/meta.go
- sdk/plugin.go
- sdk/sdk.go
- sdk/server.go
- sdk/utils.go
- sdk/version.go
This is yet another pass at slowly reorganizing things to have better scoping, flow, etc. Things are starting to come together from an overall structural level, but there is still a bunch that needs to be done to realize it fully.
> more updates to plugin flow/sdk organization

- sdk/cache.go
- sdk/data_manager.go
- sdk/plugin.go
- sdk/state_manager.go
this is mostly an organizational change which starts moves the state handling from multiple places (device_manager, cache.go, transaction.go) into a single place. this will make it easier to follow the flow of data through a plugin.
> create the StateManager to be the handler of device state

- sdk/config/plugin.go
- sdk/constants.go
- sdk/data_manager.go
- sdk/device_manager.go
- sdk/output/output.go
- sdk/plugin.go
- sdk/scheduler.go
- sdk/server.go
- sdk/transaction.go
- sdk/utils/time.go
again, basically just reorganization, splitting up the data_manager into the scheduler and state_manager.
> add scheduler component to handle device reads/writes/listens

- sdk/device_manager.go
- sdk/server.go
- sdk/tag.go
> add tag caching and tag filtering capabilities

- sdk/config/device.go
- sdk/data_manager.go
- sdk/device.go
- sdk/device_handler.go
- sdk/device_manager.go
- sdk/healthchecks.go
- sdk/models.go
- sdk/output/output.go
- sdk/plugin.go
- sdk/scheduler.go
- sdk/server.go
- sdk/state_manager.go
- sdk/validate.go
> update references to use v3 device modeling

- examples/simple_plugin/config/device/led.yaml
- examples/simple_plugin/config/device/test.yaml
- examples/simple_plugin/plugin.go
This updates the simple plugin to use the updated SDK. This will be useful for testing and developing against.
> update simple example plugin for v3

- sdk/config/config.go
- sdk/config/config_test.go
- sdk/meta_test.go
- sdk/output/output.go
- sdk/output/output_test.go
- sdk/output/reading_test.go
- sdk/utils/convert_test.go
- sdk/utils/time_test.go
- sdk/version_test.go
this PR doesn't add much that is new, just fixes some commented out tests and update tests for some things that were moved around.
> adding and updating unit tests

- examples/simple_plugin/plugin.go
- sdk/config/config.go
- sdk/output/color.go
- sdk/output/duration.go
- sdk/output/electric_current.go
- sdk/output/electric_resistance.go
- sdk/output/frequency.go
- sdk/output/humidity.go
- sdk/output/pressure.go
- sdk/output/rotational_speed.go
- sdk/output/speed.go
- sdk/output/state.go
- sdk/output/status.go
- sdk/output/temperature.go
- sdk/output/voltage.go
- sdk/plugin.go
#330 #331 
the conversion functions still need tests written against them, but this is just a start to get them in place. may need to update the existing ones / add more in the future.
> add some basic built-in output types

- sdk/config/device.go
- sdk/device.go
- sdk/health/status.go
- sdk/health/summary.go
- sdk/meta.go
- sdk/models.go
- sdk/output/output.go
- sdk/output/reading.go
- sdk/scheduler.go
- sdk/server.go
- sdk/state_manager.go
- sdk/tag.go
- sdk/transaction.go
- sdk/version.go
> add support for write timeouts

- .jenkins
- sdk/transaction_test.go
> minor initial updates to dev flow

- sdk/device.go
- sdk/device_manager.go
- sdk/tag.go
> add basic system-generated tags

- Gopkg.lock
- examples/simple_plugin/config.yml
- examples/simple_plugin/plugin.go
- sdk/config/device.go
- sdk/device.go
- sdk/device_manager.go
- sdk/output/reading.go
- sdk/plugin.go
- sdk/scheduler.go
- sdk/server.go
- sdk/state_manager.go
- sdk/tag.go
- sdk/transaction.go
this PR gets the read/write/transaction flow all hooked up in the server. it also fixes various bugs and adds in other updates that were needed for the read/write flow updates.
> server updates to get reads and writes working

- sdk/device_manager.go
- sdk/plugin.go
- sdk/scheduler.go
- sdk/server.go
- sdk/state_manager.go
> update plugin and component constructors

- internal/test/grpc.go
- sdk/server.go
- sdk/server_test.go
- adds tests for the server component
> add unit tests, pt. 5

- sdk/device_manager.go
- sdk/health/manager.go
- sdk/health/manager_test.go
- sdk/plugin.go
- sdk/plugin_test.go
- sdk/testdata/plugin/config.yml
- sdk/testdata/plugin/ok/config.yml
> add unit tests, pt. 6

- sdk/state_manager_test.go
adds unit tests for the state manager
> add unit tests, pt. 7

- sdk/scheduler.go
- sdk/scheduler_test.go
adds unit tests for the scheduler component
> add unit tests, pt. 8

- sdk/device.go
- sdk/device_handler.go
- sdk/device_handler_test.go
- sdk/device_manager.go
- sdk/device_manager_test.go
- sdk/device_test.go
- sdk/server_test.go
- sdk/state_manager.go
- sdk/state_manager_test.go
> updates for various missing device capabilities

- sdk/device.go
- sdk/device_test.go
- sdk/output/output.go
- sdk/output/output_test.go
- sdk/output/reading.go
- sdk/output/reading_test.go
- sdk/plugin.go
- sdk/plugin_test.go
- sdk/server.go
- sdk/server_test.go
- sdk/state_manager.go
- sdk/state_manager_test.go
> add output to grpc device response

- Gopkg.lock
- examples/multi_device_plugin/config.yml
- examples/multi_device_plugin/devices/air8884.go
- internal/test/grpc.go
- sdk/server.go
- sdk/server_test.go
related to the changes in: https://github.com/vapor-ware/synse-server-grpc/pull/46
> updates for recent grpc changes/fixes

- sdk/scheduler.go
- sdk/server.go
- sdk/transaction.go
> add write context to grpc transaction responses

- sdk/config/plugin.go
> set the default read/write interval to 1s

- sdk/device.go
- sdk/device_test.go
- sdk/server_test.go
> expose write capabilities if appropriate for a device

- sdk/config/config.go
- sdk/device.go
- sdk/device_manager.go
- sdk/id.go
- sdk/options.go
- sdk/plugin.go
> add logging where it was missing

- Makefile
> update and clean up makefile targets

- examples/c_plugin/config.yml
- examples/device_actions/config.yml
- examples/dynamic_registration/config.yml
- examples/health_check/config.yml
- examples/listener/config.yml
- examples/multi_device_plugin/config.yml
- examples/simple_plugin/config.yml
- sdk/health/manager.go
- sdk/plugin.go
- sdk/plugin_test.go
- fixes bug where health manager was not being initialized or started
- adds more logging for the health manager, particularly around health state changes
> fix bugs with health manager, add logging

- sdk/device.go
This PR:
- adds in a log message which was previously missing
fixes #455
> log: add in missing log statement

- sdk/plugin.go
This PR:
- adds the `--pprof` flag to enable an HTTP server providing plugin profiling info via pprof. This is useful for debugging and investigating issues such as memory leaks.
I added this to investigate issues in a plugin being developed and figured it would be good to have built into the SDK so it is available to all plugins.
> feat: add flag for built-in plugin profiling via pprof

- sdk/device_manager.go
- sdk/server.go
- sdk/server_test.go
- sdk/state_manager_test.go
This PR:
- adds in an error return which was missing
- formats code based on lint suggestions
> fix missing err return

- .jenkins
- Makefile
- scripts/build_examples.sh
- scripts/run_examples.sh
This PR:
- updates the CI pipeline to use the ci-shared lib
> ci: update CI to use shared jenkins pipeline

- sdk/stream.go
- sdk/stream_test.go
This PR:
- updates the ReadStream to have locking around channel writes and drain channels prior to closing them. if a channel has something in it that has not been read when it is closed, it will panic. the locking is to prevent a race condition where `close` is called, but the goroutine is still attempting to write to a channel.
- renames `closing` to `closed`, so it makes a bit more sense when accessing it (e.g. `if stream.closed`)
Its not clear whether the root cause behind the linked issue was related to either or both of these fixes, as there isn't enough visibility in the logs/panic output to determine for sure, but either way, these seem like updates we will want.
[VIO-1237]
[VIO-1237]: https://vaporio.atlassian.net/browse/VIO-1237
> drain stream channels prior to closing
